server:
  port: 8090

  
spring:
  application:
    name: metircs-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: account
        uri: http://127.0.0.1:8080
        predicates:
        - Path= /account/**
        filters:
        - PrefixPath=/metircs
      - id: baidu
        uri: https://www.baidu.com
        predicates:
        - Path= /baidu/**
      - id: sina
        uri: https://www.sina.com
        predicates:
        - Path= /sian/**
      
  
    
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-expiration-duration-in-seconds: 10 #10秒不发就过期
    lease-renewal-interval-in-seconds: 5 # 5秒发送一次心跳
    ip-address: 127.0.0.1
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
    

mygateway:
#  urls:
#  - /baidu/**
  effective-time: 1m
    
    
    
    